---
- name: Gather commands
  gather_facts: no
  hosts: all
  vars:
    commands:
      - show version
      - show ip int br
      - show memory statistics
      - show arp
      - show ip route
      - show interfaces
  tasks:
    - name: Gather commands
      ios_command:
        commands: "{{ commands }}"
      register: output

    - name: Save output to a file
      copy:
        content: "{{ output.stdout | zip(commands) | flatten | join('\n') }}"
        dest: "output/{{ inventory.hostname }}.txt"